nome = input ("Qual é o seu nome?")
print ("Olá", nome, "!Prazer em te conhecer!")
idade = input ("Qual é a sua idade?")
peso = input ("Qual é o seu peso?")
print ("Então tu tens", idade, "anos e", peso, "Kg.")
