a = input("Digite algo:")
print("False em português é falso e true em português é verdadeiro ou verdade")
print("É o tipo: ", type(a))
print("É um tipo númerico: ", a.isnumeric())
print("Contem letras do alfabeto: ", a.isalpha())
print("É um tipo alfabetico e/ou númerico: ", a.isalnum())
print("É uma palavra que so contém letras maiusculas: ", a.isupper())
print("É uma palavra que so contém letras minusculas: ", a.islower())
print("So tem espaços: ", a.isspace())
print("no inicio de cada palavra ou adjetivo ou verbo ou etc...: ", a.istitle())